services:
  - type: web
    name: gitiharihar-website
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
